# Generated by Django 5.1.6 on 2025-02-21 21:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habitschedule",
            old_name="day_of_week",
            new_name="day",
        ),
        migrations.AlterUniqueTogether(
            name="habitschedule",
            unique_together={("habit", "day")},
        ),
        migrations.CreateModel(
            name="HabitTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("completed", models.BooleanField(default=False)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackers",
                        to="habit.habit",
                    ),
                ),
            ],
            options={
                "unique_together": {("habit", "date")},
            },
        ),
        migrations.DeleteModel(
            name="HabitProgress",
        ),
    ]
